# Generated by Django 3.2.7 on 2021-09-26 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pensum', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='programa',
            table='programa',
        ),
    ]
